# _config.yml file used to define gloal setting for entire site

title: WiCyS @ RIT
description: Women in Cybersecurity at Rochester Intitute of Technology
# baseurl: , what do it place here?
url: https://wicysrit.com # custom domain

# Build settings

theme: null # not needed, everything customized
plugins: 
  - jekyll-seo-tags # rtisec uses jekyll-seo-tags, deepseek reccomended jekyll-feed(but its not a blog)
permalink: /:title # the slug of each pages url will be the pages tite: https://wicys.com/e-board

 


